name: 'App-Offline'
description: 'Creates or removes the app_offline.html file on/from a remote server via ftp'
inputs:
  app_state:
    description: '(online|offline): Creates file if offline is specified and removes file if online is specified'
    required: true
  ftp_server:
    description: 'FTP server name (you may need to specify a port)'
    required: true
  ftp_username:
    description: 'FTP account username'
    required: true
  ftp_password:
    description: 'FTP account password'
    required: true
  method:
    description: 'Protocol used to deploy (ftp or sftp)'
    required: false
    default: "ftp"
  port:
    description: 'The port used to connect to server'
    required: false
    default: "21"
  remote_dir:
    description: 'The remote folder to copy to, defaults to root FTP folder'
    required: false
    default: ""
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.app_state }}
    - ${{ inputs.ftp_server }}
    - ${{ inputs.ftp_username }}
    - ${{ inputs.ftp_password }}
    - ${{ inputs.method }}
    - ${{ inputs.port }}
    - ${{ inputs.remote_dir }}